spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:./h2-test
    username: sa

  h2:
    console:
      enabled: false
      settings:
        web-admin-password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: db/changelog/changelog.yml
    enabled: true
    password: password
    user: sa
    url: jdbc:h2:./h2-test


bot:
  name: core_english_test_bot
  token: 5962810244:AAG0QSUXQi0etiagdEDI4mkuXrvRSpH70yo
  chatId: 5962810244


notification:
  upcoming-lesson-threshold: PT2H
  upcoming-lesson-cron: '0 * * * * *'

statistics:
  student:
    pdf-template-name: 'thymeleaf_template'

messages:
  text-maker:
    lesson-info-pattern: |
      Данные об уроке
      Тема: %s
      Статус: %s
      Дата проведения: %s
      Оценка: %s
      Ссылка: %s
    more-lesson-info-pattern: |
      
      
      Урок: %s
      Статус: %s
      Дата проведения: %s
    data-missing: 'Не установлена'
    link-pattern: '[Перейти](%s)'

  gateway:
    failed-to-identify: 'Не удалось найти вас в системе. Напишите /start для начала работы или свяжитесь со службой поддержки.'

  services:
    notification:
      lesson-date-changed-notification: 'Урок "%s" с одной из ваших подписок сменил дату проведения на %s'
      upcoming-lesson-notification: 'Урок "%s" с одной из ваших подписок начнется менее, чем через %s. Точное начало урока: %s'
    subscription:
      lesson-topic: 'Урок №%s'

  handlers:
    assign-role-for-guest:
      choose-guest: 'Выберите гостя:'
      guests-not-found: 'Незарегистрированных пользователей в системе не найдено.'
      choose-role: 'Выберите новую роль гостю:'
      success: 'Для пользователя "%s" успешно установлена роль "%s"'

    cancel-lesson:
      done: 'Урок отменён.'
      ended: 'Невозможно отменить урок. Он уже завершён.'
      in-progress: 'Невозможно отменить урок. Он уже начат.'

    cancel-subscription:
      done: 'Абонемент отменён.'
      already-canceled: 'Невозможно отменить абонемент. Он уже неактивен.'

    create-lesson:
      start: |
        Для создания нового урока заполните и отправьте форму с данными \(каждое поле на новой строке в одном сообщении в том же порядке\)\. Пример:
        %s
      data-form: |
        `date: 20\.03\.2023 20:00`
        `topic: Topic of lesson`
        `link: https://example.link.com`
      subscription-not-active: 'Подписка, для которой вы пытаетесь добавить урок, уже не активна.'
      success: 'Новый урок добавлен.'

    create-subscription:
      start: |
        Для создания нового абонемента заполните и отправьте форму с данными \(каждое поле на новой строке в одном сообщении в том же порядке\)\. Пример:
        %s
      data-form: |
        `startDate: 11\.03\.2023`
        `endDate: 30\.04\.2023`
        `lessonAmount: 7`
      student-choose: 'Далее выберите студента, с которым будут проводиться занятия:'
      teacher-choose: 'Также выберите учителя, который будет проводить занятия:'
      success: 'Новый абонемент и требуемые уроки созданы.'

    finish-lesson:
      already-finished: 'Урок не может быть повторно завершен!'

    get-student-statistic:
      choose-student-query: 'Выберите ученика для которого нужно сгенерировать статистику:'
      enter-interval-query: |
        Укажите промежуток для получения статистики по приведенному шаблону:
        %s
      data-form: |
        `startDate: 11\.03\.2023 20:00`
        `endDate: 30\.04\.2023 20:00`
      complete: 'Сгенерированный файл статистики'
      students-not-found: 'Учеников в системе не найдено.'

    set-comment-for-parent:
      start: 'Введите следующим сообщением текст комментария для родителя.'
      success: 'Комментарий успешно сохранен.'

    set-homework-comment:
      start: 'Введите следующим сообщением текст комментария (ссылку на домашнее задание).'
      success: 'Комментарий успешно сохранен.'

    set-homework-completed:
      done: 'Домашнее задание для урока "%s" установлено, как выполненное.'

    set-homework-not-completed:
      done: 'Домашнее задание для урока "%s" установлено, как не выполненное.'

    set-lesson-date:
      start: |
        Для того, чтобы установить дату проведения урока, введите ее согласно данному формату:
        
        %s
        
        Обратите внимание, что дата проведения не должна выходить за пределы абонимента:
            Начало абонимента: %s
            Конец абонимента: %s
      data-form: '`27\.03\.2023 20:00`'
      success: 'Дата проведения урока "%s" упешно установлена.'

    set-mark:
      message: 'Занятию установлена оценка: %s'

    set-mark-menu:
      message: 'Выберите оценку:'

    set-parent-for-student:
      choose-student: 'Выберите ученика:'
      choose-parent: 'Выберите родителя:'
      success: 'Для ученика "%s" успешно установлен родитель "%s"'
      students-not-found: 'Учеников в системе не найдено.'
      parents-not-found: 'Родителей в системе не найдено.'

    set-user-role:
      user-role-successfully-changed-message: 'Ваша роль изменена на: %s'
      failed-to-change-user-role-message: 'Невозможно сменить роль на такую же, как у вас.'

    assign-role:
      message: 'Выберите новую роль:'

    get-all-students:
      start: 'Список зарегистрированных студентов:'
      no-students: 'Зарегистрированные студенты отсутствуют в системе.'

    get-all-subscriptions:
      no-family-subscriptions: 'В вашей семье нет активных абонементов.'
      no-teacher-subscriptions: 'Нет активных абонементов, в которых вы являетесь преподавателем.'
      no-student-subscriptions: 'Нет активных абонементов, в которых вы являетесь студентом.'
      no-subscriptions: 'В системе нет активных абонементов.'
      data-pattern: |
        Тип: %s
        Статус: %s
        Уроков осталось: %d
  
        Учитель: %s
        Студент: %s
  
        Дата начала: %s,
        Дата завершения: %s

    get-all-teachers:
      start: 'Список зарегистрированных преподавателей:'
      no-teachers: 'Зарегистрированные преподаватели отсутствуют в системе.'

    get-all-unfinished-tasks:
      start: 'Список предстоящих (невыполненных) ДЗ:'
      task-info-pattern: |
        Тема занятия: %s
        Дата проведения: %s
        Задание: %s
      task-link-pattern: '[Ссылка к ИДЗ](%s)'
      no-tasks: 'Предстоящие (невыполненные) ДЗ отсутствуют.'

    show-comment-for-parent:
      data-pattern: 'Комментарий для родителя: %s'

    show-homework-comment:
      data-pattern: 'Комментарий учителя (домашнее задание): %s'

    show-mark:
      data-pattern: 'Оценка за занятие: %s'

    data-menu:
      message: 'Вы перешли в раздел РАБОТА С ДАННЫМИ'

    get-statistics-menu:
      message: 'Вы перешли в раздел СТАТИСТИКА'

    start:
      greeting: 'Добро пожаловать, %s. Ваша роль: %s'

    to-main-menu:
      message: 'Вы вернулись в ГЛАВНОЕ МЕНЮ'

    work-with-subscriptions:
      message: 'Вы перешли в раздел РАБОТА С АБОНЕМЕНТАМИ'