name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Maven Package
        run: mvn -B clean package